config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :name, :surname, :phone
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new
  end

  def create
    sanitized_params = params.require(:user).permit(:name, :surname, :phone)
    user = User.new(sanitized_params)

    if user.save
      "El usuario se guardo bien"
    else
      "El usuario no se guardo"
    end
  end

  def index
    @list_user=User.all.map{|user| {name: user.name, surname: user.surname, phone: user.phone}}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
%h1 Este es el home de mi alicacion
= link_to "ver usuarios", users_path
- # debe haber un enlace para crear o listar usuarios
- # crear usuario -> redireccion a /users/new
- # listar usuarios -> redireccion a /users

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HoytrabajasTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/users/_form.html.haml
= react_component('NewUserForm', path: users_path)

app/views/users/index.haml
= react_component("IndexTable", listUser:@list_user)

app/views/users/new.html.haml
= render "form"